# Frozen Lake 4*4

Winter is here. You and your friends were tossing around a frisbee at the park when you made a wild throw that left the frisbee out in the middle of the lake. The water is mostly frozen, but there are a few holes where the ice has melted. If you step into one of those holes, you'll fall into the freezing water. At this time, there's an international frisbee shortage, so it's absolutely imperative that you navigate across the lake and retrieve the disc. However, the ice is slippery, so you won't always move in the direction you intend.

The surface is described using a grid like the following:

SFFF       (S: starting point, safe)

FHFH       (F: frozen surface, safe)

FFFH       (H: hole, fall to your doom)

HFFG       (G: goal, where the frisbee is located)


The episode ends when you reach the goal or fall in a hole. You receive a reward of 100 if you reach the goal, -100 if you fall into the hole, and -0.1 for each step you take.


[link](https://github.com/openai/gym/blob/master/gym/envs/toy_text/frozen_lake.py) of the document.

## Getting Started

Run the following code and observe the result.

In [7]:
!pip install gym

In [8]:
import gym
 
MAX_ITERATIONS = 10
 
env = gym.make("FrozenLake-v0")
env.reset()
# env.render()
for i in range(MAX_ITERATIONS):
    random_action = env.action_space.sample()
    new_state, reward, done, info = env.step(random_action)

    env.render()
    
    if done:
        break

  (Down)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG


### Code explain

action space in frozen lake.

In [9]:
print(env.action_space)

Discrete(4)


In [10]:
random_action = env.action_space.sample()

print(random_action)

1


observation space in frozen lake

In [11]:
print(env.observation_space)

Discrete(16)


In [12]:
env.reset()

for _ in range(10):
  random_action = env.action_space.sample()
  new_state, _, _, _ = env.step(random_action)

  print('\n\n----------------------------')
  print('action : ',random_action)
  print('new state : ',new_state)

  env.render()



----------------------------
action :  2
new state :  4
  (Right)
SFFF
FHFH
FFFH
HFFG


----------------------------
action :  2
new state :  5
  (Right)
SFFF
FHFH
FFFH
HFFG


----------------------------
action :  2
new state :  5
  (Right)
SFFF
FHFH
FFFH
HFFG


----------------------------
action :  2
new state :  5
  (Right)
SFFF
FHFH
FFFH
HFFG


----------------------------
action :  1
new state :  5
  (Down)
SFFF
FHFH
FFFH
HFFG


----------------------------
action :  3
new state :  5
  (Up)
SFFF
FHFH
FFFH
HFFG


----------------------------
action :  0
new state :  5
  (Left)
SFFF
FHFH
FFFH
HFFG


----------------------------
action :  1
new state :  5
  (Down)
SFFF
FHFH
FFFH
HFFG


----------------------------
action :  1
new state :  5
  (Down)
SFFF
FHFH
FFFH
HFFG


----------------------------
action :  1
new state :  5
  (Down)
SFFF
FHFH
FFFH
HFFG


now guess what's the state and action

In [13]:
env.reset()

for i in range(15):
  random_action = env.action_space.sample()
  new_state, reward, done, info = env.step(random_action)
  print('\n\n--------------------------')
  print('action : {}\nnew state : {}\nreward : {}\ndone : {}\ninfo : {}'.format(random_action,new_state, reward, done, info))
  env.render()

  if done:
    break



--------------------------
action : 3
new state : 0
reward : 0.0
done : False
info : {'prob': 0.3333333333333333}
  (Up)
SFFF
FHFH
FFFH
HFFG


--------------------------
action : 0
new state : 0
reward : 0.0
done : False
info : {'prob': 0.3333333333333333}
  (Left)
SFFF
FHFH
FFFH
HFFG


--------------------------
action : 2
new state : 1
reward : 0.0
done : False
info : {'prob': 0.3333333333333333}
  (Right)
SFFF
FHFH
FFFH
HFFG


--------------------------
action : 1
new state : 5
reward : 0.0
done : True
info : {'prob': 0.3333333333333333}
  (Down)
SFFF
FHFH
FFFH
HFFG


## modify reward

set a proper reward function

In [14]:
holes = [5,7,11]
goal = 15

def Reward_Function(state):
  if state in holes :
    return -1
  if state == goal :
    return 1
  return 0

## find out values for a random policy

In [15]:
import numpy as np

np.random.choice?

In [18]:
policy = np.random.choice(range(4),replace=True,size=16)
print(policy.reshape(4,4),'\n\n\n')

env.reset()
env.render()

[[3 0 3 0]
 [1 3 1 0]
 [1 0 2 1]
 [0 1 0 0]] 




SFFF
FHFH
FFFH
HFFG


In [ ]:
generate values for each state 10 min + 15 min

# env.env.s = start_state


## make the optimal policy and evaluate that

In [ ]:
try to make the optimal policy
evaluate that

10 min

compare two policies ??????